apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: day2configuration-argocd-applications
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: >-
      https://github.com/Redhat-Openshift-GitOps-Workshop/day2configuration-argocd-applications
    targetRevision: main
    helm:
      valueFiles:
        - values-dev.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true